# Assumes that conda, pip and build-essentials are installed
---
name: kompuke_gpu
channels:
- conda-forge
- nvidia

dependencies:
- python=3.11.6
- conda-build
- numpy=1.26
- matplotlib=3.8.1
- jupyter
- pandas=2.1.3
- nb_conda_kernels
- nbdime
- pycuda
- ffmpeg
- cuda

# Install environment:
# $ conda env create -f conda_environment.yml

# Activate environment:
# $ conda activate kompuke_gpu
